// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"time"
)

type GeyserHistory struct {
	ID          int32
	Action      string
	ResidentKey string
	CreatedAt   time.Time
}

type GeyserStatus struct {
	IsOn      bool
	ActionBy  string
	UpdatedAt time.Time
}

type Resident struct {
	Key         string
	DisplayName string
}
