// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: residents.sql

package repository

import (
	"context"
)

const getResidentByKey = `-- name: GetResidentByKey :one
select ` + "`" + `key` + "`" + `, display_name from residents where ` + "`" + `key` + "`" + ` = ?
`

func (q *Queries) GetResidentByKey(ctx context.Context, userkey string) (Resident, error) {
	row := q.db.QueryRowContext(ctx, getResidentByKey, userkey)
	var i Resident
	err := row.Scan(&i.Key, &i.DisplayName)
	return i, err
}
